services:
  prometheus:
    image: prom/prometheus:v3.8.0
    container_name: prometheus
    volumes:
      - /volume1/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - monitoring
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=/prometheus'
      - '--web.route-prefix=/'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.3.3
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_DOMAIN=192.168.1.5
      - GF_SERVER_ROOT_URL=http://192.168.1.5:8080/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    depends_on:
      - prometheus
    restart: unless-stopped

  snmp-exporter:
    image: prom/snmp-exporter:v0.25.0
    container_name: snmp-exporter
    volumes:
      - /volume1/monitoring/snmp-exporter/snmp.yml:/etc/snmp-exporter/snmp.yml
    networks:
      - monitoring
    command:
      - '--config.file=/etc/snmp-exporter/snmp.yml'
    restart: unless-stopped

  nginx:
    image: nginx:1.28.2
    container_name: nginx
    volumes:
      - /volume1/monitoring/nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
    networks:
      - monitoring
    depends_on:
      - prometheus
      - grafana
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge
