global:
  scrape_interval: 30s
  scrape_timeout: 25s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'snmp_exporter'
    static_configs:
      - targets: ['nas-monitoring-snmp-exporter-1:9116']

  - job_name: 'synology_snmp'
    metrics_path: /snmp
    params:
      module: [synology]
    scrape_interval: 30s
    scrape_timeout: 25s
    static_configs:
      - targets: ['192.168.1.5']  # Your Synology NAS IP
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116