{
 "title": "Synology SNMP",
 "description": "Dashboard for viewing Synology System Information using Prometheus and SNMP_Exporter",
 "tags": [
  "synology",
  "dsm",
  "snmp"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Server:", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(modelName, instance)"
    }
   },
   { "name": "job", "label": "Job", "query": { "query": "label_values(modelName, job)" } },
   { "name": "interfacebits", "query": "8" },
   {
    "name": "Interface",
    "query": {
     "query": "label_values(ifName{job=~'$job',instance=~'$instance'},ifName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Summary - $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modelName{job=~'$job',instance=~'$instance'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Serial",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "serialNumber{job=~'$job',instance=~'$instance'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "gauge",
   "description": "The percentage of CPU time spent processing user-level code, calculated over the last minute.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ssCpuIdle{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "System Temp",
   "type": "gauge",
   "description": "The temperature of Disk Station uses Celsius degree",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100 / memTotalReal{job=~'$job',instance=~'$instance'}) * (memTotalReal{job=~'$job',instance=~'$instance'} - memAvailReal{job=~'$job',instance=~'$instance'} - memCached{job=~'$job',instance=~'$instance'} - memBuffer{job=~'$job',instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(memTotalSwap{job=~'$job',instance=~'$instance'} - memAvailSwap{job=~'$job',instance=~'$instance'}) / memTotalSwap{job=~'$job',instance=~'$instance'} * 100"
    }
   ]
  },
  {
   "title": "Volume 1 Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"})",
     "legendFormat": "Volume 1"
    }
   ]
  },
  {
   "title": "Volume 2 Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 2\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 2\"})",
     "legendFormat": "Volume 2"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memTotalReal{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memTotalSwap{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cpuFanStatus{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "systemFanStatus{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "systemStatus{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "powerStatus{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "targets": [
    {
     "expr": "upgradeAvailable{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "version{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "RAID Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "raidStatus{job=~'$job',instance=~'$instance', raidName=~\"Volume.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hard Drives",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "diskTemperature{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "diskType{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "diskStatus{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "diskModel{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  { "title": "CPU / RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Utilisation - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ssCpuUser{job=~'$job',instance=~'$instance'}",
     "legendFormat": "User"
    },
    {
     "expr": "ssCpuSystem{job=~'$job',instance=~'$instance'}",
     "legendFormat": "System"
    },
    {
     "expr": "100 - ssCpuIdle{job=~'$job',instance=~'$instance'} - ssCpuUser{job=~'$job',instance=~'$instance'} - ssCpuSystem{job=~'$job',instance=~'$instance'}",
     "legendFormat": "I/O Wait"
    }
   ]
  },
  {
   "title": "System Load (minute ave.) - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "laLoadInt{job=~'$job',instance=~'$instance', laNames=\"Load-1\"} / 100",
     "legendFormat": "{{laNames}}"
    },
    {
     "expr": "laLoadInt{job=~'$job',instance=~'$instance', laNames=\"Load-5\"} / 100",
     "legendFormat": "{{laNames}}"
    },
    {
     "expr": "laLoadInt{job=~'$job',instance=~'$instance', laNames=\"Load-15\"} / 100",
     "legendFormat": "{{laNames}}"
    }
   ]
  },
  {
   "title": "RAM Utilisation - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 / memTotalReal{job=~'$job',instance=~'$instance'}) * (memTotalReal{job=~'$job',instance=~'$instance'} - memAvailReal{job=~'$job',instance=~'$instance'} - memCached{job=~'$job',instance=~'$instance'} - memBuffer{job=~'$job',instance=~'$instance'})",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Physical Memory - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "memTotalReal{job=~'$job',instance=~'$instance'} ",
     "legendFormat": "Size"
    },
    {
     "expr": "memTotalReal{job=~'$job',instance=~'$instance'} - (memShared{job=~'$job',instance=~'$instance'} + memCached{job=~'$job',instance=~'$instance'} + memBuffer{job=~'$job',instance=~'$instance'} + memAvailReal{job=~'$job',instance=~'$instance'})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "memBuffer{job=~'$job',instance=~'$instance'}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "memCached{job=~'$job',instance=~'$instance'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "memShared{job=~'$job',instance=~'$instance'}",
     "legendFormat": "Shared"
    },
    {
     "expr": "memAvailReal{job=~'$job',instance=~'$instance'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "SWAP Utilisation % - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(memTotalSwap{job=~'$job',instance=~'$instance'} - memAvailSwap{job=~'$job',instance=~'$instance'}) / memTotalSwap{job=~'$job',instance=~'$instance'} * 100",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "SWAP Utilisation - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "memTotalSwap{job=~'$job',instance=~'$instance'}",
     "legendFormat": "Size"
    },
    {
     "expr": "(memTotalSwap{job=~'$job',instance=~'$instance'} - memAvailSwap{job=~'$job',instance=~'$instance'})",
     "legendFormat": "Used"
    },
    {
     "expr": "memAvailSwap{job=~'$job',instance=~'$instance'}",
     "legendFormat": "Free"
    }
   ]
  },
  { "title": "HDD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Storage Usage % - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"})",
     "legendFormat": "Volume 1"
    },
    {
     "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 2\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 2\"})",
     "legendFormat": "Volume 2"
    },
    {
     "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 3\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 3\"})",
     "legendFormat": "Volume 3"
    },
    {
     "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 4\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 4\"})",
     "legendFormat": "Volume 4"
    },
    {
     "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 5\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 5\"})",
     "legendFormat": "Volume 5"
    },
    {
     "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 6\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 6\"})",
     "legendFormat": "Volume 5"
    }
   ]
  },
  {
   "title": "Storage Usage - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"} - raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"}",
     "legendFormat": "Volume 1"
    },
    {
     "expr": "raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 2\"} - raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 2\"}",
     "legendFormat": "Volume 2"
    },
    {
     "expr": "raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 3\"} - raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 3\"}",
     "legendFormat": "Volume 3"
    },
    {
     "expr": "raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 4\"} - raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 4\"}",
     "legendFormat": "Volume 4"
    },
    {
     "expr": "raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 5\"} - raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 5\"}",
     "legendFormat": "Volume 5"
    },
    {
     "expr": "raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 6\"} - raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 6\"}",
     "legendFormat": "Volume 5"
    }
   ]
  },
  { "title": "exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "SNMP Exporter - Scrape Time - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "snmp_scrape_duration_seconds{job=~'$job',instance=~'$instance'}",
     "legendFormat": "{{label_name}}{{job}}"
    }
   ]
  }
 ]
}